name: merge
on:
  pull_request:
    branches:
      - master
permissions:
  contents: write
  pull-requests: write
jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.id == vars.NIXINTOSH_BOT_USER_ID
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
          PR_N: ${{ github.event.pull_request.number }}
        run: |
          gh pr review "${PR_N}" -a
          gh pr merge "${PR_N}" -m --auto
