name: test
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      arch: ${{ steps.arch.outputs.json }}
      attr: ${{ steps.attr.outputs.json }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v24
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install
          nix_path: nixpkgs=channel:nixpkgs-22.11-darwin
      - name: fetch repository
        run: |
          git fetch --all --filter=tree:0
      - name: compute arch
        id: arch
        run: |
          make -C ./hack/workflows/ arch.json
          echo "json=$(cat ./hack/workflows/arch.json)" >> "${GITHUB_OUTPUT}"
      - name: compute attr
        id: attr
        run: |
          make -C ./hack/workflows/ attr.json
          echo "json=$(cat ./hack/workflows/attr.json)" >> "${GITHUB_OUTPUT}"
  main:
    runs-on: macos-latest
    needs: matrix
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJSON(needs.matrix.outputs.arch) }}
        attr: ${{ fromJSON(needs.matrix.outputs.attr) }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install nix
        uses: cachix/install-nix-action@v24
        with:
          install_url: https://releases.nixos.org/nix/nix-2.18.1/install
          nix_path: nixpkgs=channel:nixpkgs-22.11-darwin
      - name: make test
        env:
          NIXPKGS_ALLOW_UNFREE: '1'
        run: |
          make -C ./hack/workflows/ test-'${{ matrix.arch }}' ATTR='${{ matrix.attr }}'
  exit:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - name: exit
        run: |
          exit
